<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Introduction to factiv • factiv</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/cosmo/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Introduction to factiv">
<meta property="og:description" content="factiv">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">factiv</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.0.0.9001</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/factiv.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/mattblackwell/factiv/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="factiv_files/header-attrs-2.7/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Introduction to factiv</h1>
            
            <h4 class="date">2021-04-27</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/mattblackwell/factiv/blob/master/vignettes/factiv.Rmd"><code>vignettes/factiv.Rmd</code></a></small>
      <div class="hidden name"><code>factiv.Rmd</code></div>

    </div>

    
    
<div id="factiv-noncompliance-and-instrumental-variables-in-factorial-experiments" class="section level1">
<h1 class="hasAnchor">
<a href="#factiv-noncompliance-and-instrumental-variables-in-factorial-experiments" class="anchor"></a>factiv: Noncompliance and Instrumental Variables in Factorial Experiments</h1>
<p>The factiv package allows analysts to address noncompliance in <span class="math inline">\(2^K\)</span> factorial experiments using instrumental variables methods. The package implements the methods of <span class="citation">Blackwell and Pashley (2021)</span>. A <span class="math inline">\(2^K\)</span> factorial experiment randomly assigns units to <span class="math inline">\(2^K\)</span> possible treatment combinations of <span class="math inline">\(K\)</span> binary factors, and allows analysts to estimate the main and interactive effects of the factors, which we call factorial effects.</p>
<p>With noncompliance, the factorial effects of treatment uptake are not identified since noncompliance might be related to the outcomes. <span class="citation">Blackwell and Pashley (2021)</span> introduce a set of complier-average factorial effects that factiv is designed to estimate.</p>
<div id="what-are-factorial-effects" class="section level2">
<h2 class="hasAnchor">
<a href="#what-are-factorial-effects" class="anchor"></a>What are factorial effects?</h2>
<p>In factorial experiments, several factors are being randomized at the same time. The <code>newhaven</code> data in the factiv package gives one example of such a factorial experiment involving a get-out-the-vote experiment where households were randomly assigned to receive (a) in-person canvassing or not, and (b) phone canvassing or not. Thus, in this experiment (which we call a 2x2 factorial design), there are four possible treatment assignments corresponding to the four combinations of the two binary treatments.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/mattblackwell/factiv">factiv</a></span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">newhaven</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span>
  `In-Person` <span class="op">=</span> <span class="va">newhaven</span><span class="op">$</span><span class="va">inperson_rand</span>,
  `Phone` <span class="op">=</span> <span class="va">newhaven</span><span class="op">$</span><span class="va">phone_rand</span>
<span class="op">)</span></code></pre></div>
<pre><code>##          Phone
## In-Person    0    1
##         0 5645  633
##         1 1445  142</code></pre>
<p>In factorial experiments, there are two types of quantities of interest we may want to estimate: main effects and interactions. Main effects are defined as the effect of one factor, marginalizing over the assignment of the other factor. For the <code>newhaven</code> experiment in-person canvassing, this would be the average of the effect of in-person canvassing when assigned phone contact and the effect when assigned to no phone contact. An interaction is how the effect of a factor changes as a function of another factor. The in-person/phone interaction, then is the <em>difference</em> between the effect of in-person canvassing when assigned phone contact and the effect when not assigned to phone contact. These quantities of interest can be easily estimated using functions of sample means within each treatment combination.</p>
</div>
<div id="what-is-noncompliance" class="section level2">
<h2 class="hasAnchor">
<a href="#what-is-noncompliance" class="anchor"></a>What is noncompliance?</h2>
<p>Noncompliance occurs when respondents don’t take their assigned treatment. We say that treatment uptake differs from treatment assignment. We can see this in the <code>newhaven</code> experiment, with phone canvassing:</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span>
  `Phone Assignment` <span class="op">=</span> <span class="va">newhaven</span><span class="op">$</span><span class="va">phone_rand</span>,
  `Phone Uptake` <span class="op">=</span> <span class="va">newhaven</span><span class="op">$</span><span class="va">phone</span>
<span class="op">)</span></code></pre></div>
<pre><code>##                 Phone Uptake
## Phone Assignment    0    1
##                0 7090    0
##                1  626  149</code></pre>
<p>Only 149 of the 775 household assigned to the phone canvassing actually received the canvassing. Much of this noncompliance occurs because household do not answer their phones or hang up once they hear the call is a canvasser. Because the decision to comply (answer the phone) is likely correlated with the ultimate outcome, voting, we might worry that using treatment uptake might lead to biased estimates.</p>
</div>
<div id="complier-effects-in-factorial-experiments" class="section level2">
<h2 class="hasAnchor">
<a href="#complier-effects-in-factorial-experiments" class="anchor"></a>Complier effects in factorial experiments</h2>
<p>To overcome these issues, factiv takes an instrumental variables approach and focuses on estimating the factorial effect among <em>compliers</em>, or those respondents who would comply with their assigned treatment. <span class="citation">Blackwell and Pashley (2021)</span> identified two types of complier effects in the factorial setting: marginalized complier average factorial effects (MCAFEs) and perfect complier average factorial effects (PCAFE). These effects are simplest to understand for main effects:</p>
<ul>
<li>
<strong>Main-effect MCAFEs</strong>: the main effect of a factor effect among those who would comply with the factor, regardless of how they would comply on other factors.</li>
<li>
<strong>Main-effect PCAFEs</strong>: the main effect of a factor effect among those who would comply with <strong>all</strong> factors.</li>
</ul>
<p>For instance, in the <code>newhaven</code> data, the MCAFE for phone canvassing is the main factorial effect of (actual) phone canvassing among those who would pick up a phone call when called, regardless of how they would comply with in-person canvassing. The PCAFE would be the same effect for respondents who comply with both factors.</p>
<p>For interaction, we refer to the <em>active factors</em> as the set of factors being interacted. Then we can define our quantities for interactions:</p>
<ul>
<li>
<strong>Interaction MCAFEs</strong>: the interaction between factors among those who would comply with those active factors, regardless of how they would comply on other factors.</li>
<li>
<strong>Interaction PCAFEs</strong>: the interaction between factors among those who would comply with <strong>all</strong> factors.</li>
</ul>
</div>
<div id="estimating-complier-effects-with-factiv" class="section level2">
<h2 class="hasAnchor">
<a href="#estimating-complier-effects-with-factiv" class="anchor"></a>Estimating complier effects with factiv</h2>
<p>factiv provides two ways of estimating the complier effects that differ in how they treat uncertainty. The first is a finite-population (or finite-sample) approach that treats outcomes as fixed and views treatment assignment as the only source of variation.</p>
<p>The <code><a href="../reference/iv_finite_factorial.html">iv_finite_factorial()</a></code> function will provide these estimates, along with confidence intervals. To specify the model, you can provide a formula with two right-hand side parts separated by <code><a href="https://rdrr.io/r/base/Logic.html">|</a></code> that indicate the treatment uptake variables for each factor (on the left of <code><a href="https://rdrr.io/r/base/Logic.html">|</a></code>) and the treatment assignment variables for each factor (on the right of <code><a href="https://rdrr.io/r/base/Logic.html">|</a></code>). For the <code>newhaven</code> data, we have:</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">out</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/iv_finite_factorial.html">iv_finite_factorial</a></span><span class="op">(</span><span class="va">turnout_98</span> <span class="op">~</span> <span class="va">inperson</span> <span class="op">+</span> <span class="va">phone</span> <span class="op">|</span> <span class="va">inperson_rand</span> <span class="op">+</span>
                             <span class="va">phone_rand</span>, data <span class="op">=</span> <span class="va">newhaven</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">out</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## iv_finite_factorial(formula = turnout_98 ~ inperson + phone | 
##     inperson_rand + phone_rand, data = newhaven)
## 
## Marginalized-complier factorial effects:
##          Estimate 95% Confidence Interval
## inperson  0.0997  (-0.0538,  0.2523)     
## phone    -0.2114  (-0.4940,  0.0352)     
## 
## Perfect-complier factorial effects:
##                Estimate 95% Confidence Interval
## inperson        0.0820  (-0.6656,  0.9921)     
## phone           0.0932  (-0.6157,  1.0967)     
## inperson:phone -0.1045  (-0.7908,  0.5747)</code></pre>
<p>factiv also provides methods for accessing tidy versions of the output from its estimation function via the broom package.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/generics/man/tidy.html">tidy</a></span><span class="op">(</span><span class="va">out</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 7
##   term           estimand estimate ci_1_lower ci_1_upper ci_2_lower ci_2_upper
## * &lt;chr&gt;          &lt;chr&gt;       &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
## 1 inperson       MCAFE      0.0997    -0.0538     0.252          NA         NA
## 2 phone          MCAFE     -0.211     -0.494      0.0352         NA         NA
## 3 inperson       PCAFE      0.0820    -0.666      0.992          NA         NA
## 4 phone          PCAFE      0.0932    -0.616      1.10           NA         NA
## 5 inperson:phone PCAFE     -0.105     -0.791      0.575          NA         NA</code></pre>
<p>In this tidy output, there are columns for 2 sets of confidence intervals. This is because the approach to confidence intervals we use, which we call the Fieller method, can sometimes produce disjoint (or infinite-length) confidence intervals if compliance is very low.</p>
<p>The second estimation approach factiv implements is based on a superpopulation approach to inference. In this setting, we consider our sample as a random sample from an infinite superpopulation and entertain variation from both treatment assignment and that sampling process. The <code><a href="../reference/iv_factorial.html">iv_factorial()</a></code> function implements this approach:</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">out_sp</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/iv_factorial.html">iv_factorial</a></span><span class="op">(</span><span class="va">turnout_98</span> <span class="op">~</span> <span class="va">inperson</span> <span class="op">+</span> <span class="va">phone</span> <span class="op">|</span> <span class="va">inperson_rand</span> <span class="op">+</span>
                      <span class="va">phone_rand</span>, data <span class="op">=</span> <span class="va">newhaven</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">out_sp</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Main effects among perfect compliers:
##                                      tval  pval
## inperson        0.08204  0.35517  0.23099 0.817
## phone           0.09320  0.36317  0.25664 0.797
## inperson:phone -0.10452  0.29398 -0.35553 0.722
## 
## Estimated prob. of perfect compliers:  0.07969   SE =  0.02311</code></pre>
<p>The superpopulation approach also has a tidy method:</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/generics/man/tidy.html">tidy</a></span><span class="op">(</span><span class="va">out_sp</span>, conf.int <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 6
##   term           estimand estimate std.error conf.low conf.high
##   &lt;chr&gt;          &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 inperson       MCAFE      0.0997    0.0774  -0.0519    0.251 
## 2 phone          MCAFE     -0.211     0.132   -0.471     0.0478
## 3 inperson       PCAFE      0.0820    0.355   -0.614     0.778 
## 4 phone          PCAFE      0.0932    0.363   -0.619     0.805 
## 5 inperson:phone PCAFE     -0.105     0.294   -0.681     0.472</code></pre>
<p>Here, the confidence intervals are based on the usual large-sample variance estimates from the delta method and so will never be disjoint.</p>
</div>
<div id="covariate-profiling" class="section level2">
<h2 class="hasAnchor">
<a href="#covariate-profiling" class="anchor"></a>Covariate profiling</h2>
<p>One downside to estimating complier effects is that we generally cannot identify which respondents are or are not part of each group. Fortunately, <span class="citation">Blackwell and Pashley (2021)</span> showed how to estimate profiles of the different complier groups in terms of covariate means. factiv can implement this approach in the <code><a href="../reference/compliance_profile.html">compliance_profile()</a></code> function. You can pass this function a similar formula to the estimation functions above, with additional third part separated by a <code><a href="https://rdrr.io/r/base/Logic.html">|</a></code> that indicates which covariates you would like to use in the profile:</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cov_prof</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/compliance_profile.html">compliance_profile</a></span><span class="op">(</span>
  <span class="op">~</span> <span class="va">inperson</span> <span class="op">+</span> <span class="va">phone</span> <span class="op">|</span> <span class="va">inperson_rand</span> <span class="op">+</span> <span class="va">phone_rand</span> <span class="op">|</span>
    <span class="va">age</span> <span class="op">+</span> <span class="va">maj_party</span> <span class="op">+</span> <span class="va">turnout_96</span>,
  data <span class="op">=</span> <span class="va">newhaven</span><span class="op">)</span>
<span class="va">cov_prof</span></code></pre></div>
<pre><code>## $raw_table
##         term    overall   inperson      phone inperson:phone
## 1        age 49.0173656 56.3512346 61.7818218     48.6963536
## 2  maj_party  0.7298688  0.7943939  0.7470757      0.6262926
## 3 turnout_96  0.4543350  0.4893304  0.6148287      0.6951197
## 
## $std_table
##         term    overall   inperson      phone inperson:phone
## 1        age 49.0173656 0.36819497 0.64083618    -0.01611632
## 2  maj_party  0.7298688 0.14530850 0.03874941    -0.23325020
## 3 turnout_96  0.4543350 0.07028004 0.32231383     0.48355935</code></pre>
<p>This function return a data frame with sample averages of each covariate within each marginal complier group and the perfect complier group (which is the group associated with the highest-order interaction). For example, in the <code>newhaven</code> output, we see that the marginal compliers for phone canvassing are estimated to be on average roughly 61.8 years old compare to 49 in the sample overall. The <code>std_table</code> reports the relative difference between each group’s mean and the overall mean (in terms of standard deviations of the overall sample).</p>
</div>
<div id="references" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-BlaPas21" class="csl-entry">
Blackwell, Matthew, and Nicole E Pashley. 2021. <span>“Noncompliance and Instrumental Variables for <span class="math inline">\(2^K\)</span> Factorial Experiments.”</span> <em>Working Paper</em>. <a href="https://www.mattblackwell.org/files/papers/factorial-iv.pdf">https://www.mattblackwell.org/files/papers/factorial-iv.pdf</a>.
</div>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Matthew Blackwell, Nicole Pashley.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
